# PostgreSQL datasource configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/service1
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081